name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

#   build_docker:

#     runs-on: ubuntu-latest
    
#     if: contains(github.event.commits[modified], "python/main.py") || contains(github.event.commits[modified], "python/utils/__init__.py")

#     steps:
#     - uses: actions/checkout@v3
#     - name: Login to Registry
#       uses: docker/login-action@v1.14.1
#       with:
#         registry: docker.sparib.com
#         username: ${{ secrets.REG_USER }}
#         password: ${{ secrets.REG_PASS }}
#     - name: Build the Docker image
#       run: docker buildx build -t docker.sparib.com/reminder --push .
#     - name: Send update hook
#       uses: johannes-huther/webhook.sh@v1.0.0
#       env:
#         webhook_url: https://docker.sparib.com/
#         webhook_secret: ${{ secrets.WEB_SECRET }}
#         webhook_type: json
        
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.commits["modified"] }}
      
